name: flutter_module
description: 'FlutterHybridDemo 的 Flutter Module 部分。对应 easy_job_module。'
version: 1.0.0+1
publish_to: none

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.16.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  # 关键：把当前 Flutter 工程当成 Module 打包，宿主才能通过 include_flutter.groovy 引入
  module:
    androidX: true
    androidPackage: com.example.flutter_module
    iosBundleIdentifier: com.example.flutterModule
  uses-material-design: true
